# Mailflow - Development Docker Compose
# For development with hot-reload and debugging
# Includes PostgreSQL for testing database integration

version: '3.8'

services:
  # PostgreSQL Database for development/testing
  postgres:
    image: postgres:15-alpine
    container_name: mailflow-postgres-dev
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mailflow_dev
      POSTGRES_USER: mailflow_user
      POSTGRES_PASSWORD: mailflow_dev_password
    # No persistent volume - ephemeral database for testing
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mailflow_user -d mailflow_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - mailflow-dev-network

  mailflow-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: mailflow-dev
    ports:
      - "3001:3001"  # Backend API
      - "5173:5173"  # Frontend dev server
    volumes:
      # Mount source code for hot-reload
      - ./src:/app/src:ro
      - ./server:/app/server:ro
      - ./public:/app/public:ro
      - ./index.html:/app/index.html:ro
      - ./vite.config.ts:/app/vite.config.ts:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
      - ./tsconfig.node.json:/app/tsconfig.node.json:ro
      - ./.env.development:/app/.env.development:ro
      # Persistent data for development (bind mount to host directory)
      - ./mailflow-dev-data:/app/data/.mailflow:rw
      # Node modules (for performance)
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MAILFLOW_DATA_DIR=/app/data/.mailflow
      
      # PostgreSQL Connection - Option 1: Full URL (comment out to use SQLite)
      - DATABASE_URL=postgresql://mailflow_user:mailflow_dev_password@postgres:5432/mailflow_dev
      
      # PostgreSQL Connection - Option 2: Individual parameters (alternative to DATABASE_URL)
      # - POSTGRES_HOST=postgres
      # - POSTGRES_PORT=5432
      # - POSTGRES_DB=mailflow_dev
      # - POSTGRES_USER=mailflow_user
      # - POSTGRES_PASSWORD=mailflow_dev_password
      
      # Frontend settings
      - VITE_API_BASE_URL=http://localhost:3001/api
      - VITE_APP_NAME=Mailflow Dev
      - VITE_APP_VERSION=1.0.0-dev
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run dev
    networks:
      - mailflow-dev-network

  # pgAdmin for database management (optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: mailflow-pgadmin-dev
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mailflow.local
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-dev-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - mailflow-dev-network
    profiles:
      - pgadmin  # Optional service, start with: docker compose --profile pgadmin up

networks:
  mailflow-dev-network:
    driver: bridge

volumes:
  pgadmin-dev-data:
    driver: local