# MailFlow - Production Docker Compose
# Self-hosted email client with persistent data storage

version: '3.8'

services:
  mailflow:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: mailflow
    restart: unless-stopped
    ports:
      - "3000:3001"
    volumes:
      # Persistent data storage for configuration and database
      - mailflow-data:/app/data/.mailflow:rw
    environment:
      - NODE_ENV=production
      - MAILFLOW_DATA_DIR=/app/data/.mailflow
      # Override API base URL for production
      - VITE_API_BASE_URL=/api
      - VITE_APP_NAME=MailFlow
      - VITE_APP_VERSION=1.0.0
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailflow.rule=Host(`mailflow.localhost`)"
      - "traefik.http.services.mailflow.loadbalancer.server.port=3001"
    networks:
      - mailflow-network

networks:
  mailflow-network:
    driver: bridge

volumes:
  mailflow-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./mailflow-data